### ISSUE TITLE
Incorrect span's timestamp in zipking tracer

### ISSUE THREAD

**Issue by earezki** [eclipse-vertx/vertx-tracing#16]
### Questions

Configuring the Zipkin tracer,
And while using the database tracer, I've noticed that the spans doesn't get the start and end timestamps correctly.

![image](https://user-images.githubusercontent.com/11857979/103089891-b6204300-45ef-11eb-877c-d49fdfbc7a84.png)

### Version

4.0.1-SNAPSHOT

### Do you have a reproducer?

Query the database while the ALWAYS tracing options is active for Zipkin

* Link to github project/gist

### Extra

* Anything that can be relevant such as OS version, JVM version:
Zipkin deployed on K8S cluster.
Application is running locally on a windows 10 machine.
JVM version is 15.

**Comment by nkhanhquoc** [comment]
I get the same issue. I check Zipkin's JSON, there is no duration for all eventBus requests.

**Comment by nitishgoyal13** [comment]
I am using 4.0.1-SNAPSHOT and still seeing the same issue. Incorrect time stamps on the zipkin UI
![image](https://user-images.githubusercontent.com/12368831/106926118-c40ccc00-6736-11eb-8157-b10859bfc301.png)

**Comment by tsegismont** [comment]
@nitishgoyal13 #17 fixed the issue described here, and we have a test that passes. But it's fairly possible we missed something. Can you create another issue with details about your scenario (snippets, expectations, observations)? Thank you

**Comment by jvican** [comment]
Hey there, thanks for the fix @earezki. I've looked at the fix in #17 and I think there's one `span.start()` that is misplaced, this one:

https://github.com/eclipse-vertx/vertx-tracing/blob/6cafc99ed29236ad7489ef15e21bf8e77e749061/vertx-zipkin/src/main/java/io/vertx/tracing/zipkin/ZipkinTracer.java#L243

By just looking at the code, we should only call `start` for those traces that are not http because the following `handleReceive` call already starts the span inside its implementation by calling `handleStart`.
https://github.com/eclipse-vertx/vertx-tracing/blob/6cafc99ed29236ad7489ef15e21bf8e77e749061/vertx-zipkin/src/main/java/io/vertx/tracing/zipkin/ZipkinTracer.java#L262

However, in the current implementation we call start even for http spans, so we're starting traces more than once. The `span.start()` fix should be moved after the following line

https://github.com/eclipse-vertx/vertx-tracing/blob/6cafc99ed29236ad7489ef15e21bf8e77e749061/vertx-zipkin/src/main/java/io/vertx/tracing/zipkin/ZipkinTracer.java#L270

Would be nice to have this corrected in the codebase, it might be the cause for @nitishgoyal13's issues.

**Comment by vietj** [comment]
@jvican can you contribute a test and fix ?
